---
# dependencies (packages) for frab
# reference https://github.com/frab/frab/blob/master/INSTALL.md

# list of tasks.
# implied "tasks: "

- name: add "software collections" repo (CentOS)
  yum: name=centos-release-scl state=present
  when: ansible_distribution == "CentOS"

- name: enable "software collections" repo (RHEL)
  command: yum-config-manager --enable rhel-server-rhscl-7-rpms
  when: ansible_distribution == "Red Hat Enterprise Linux"

- name: install ruby2.3 package
  yum: name={{ item }} state=present
  with_items:
    - rh-ruby23
    - rh-ruby23-ruby-devel
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

- name: enable ruby2.3 scl in login shell(s)
  copy:
    src: "{{ role_path }}/files/profile-ruby23-scl.sh"
    dest: /etc/profile.d/z_ruby23-scl.sh
    owner: root
    mode: "0444"

- name: install other dependency packages
  yum: name={{ item }} state=present
  with_items:
    - git
    - nodejs
    - ImageMagick
    - file
    - gcc
    - mariadb-devel
    - MySQL-python
#    - mysql-connector-python
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"